from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..engine.models import RunSummary


@runtime_checkable
class ResultStoreProtocol(Protocol):
    """Abstract interface for all result-store backends (SQLite, HANA, …)."""

    def save_run(self, summary: RunSummary) -> None: ...

    def get_run(self, run_id: str) -> dict[str, Any] | None: ...

    def get_runs(self, dataset: str, limit: int = 100) -> list[dict[str, Any]]: ...

    def get_previous_actuals(self, dataset: str) -> dict[str, str]: ...

    def get_check_history(self, dataset: str, check_name: str, limit: int = 50) -> list[dict[str, Any]]: ...

    def get_metric_series(self, dataset: str, limit: int = 200) -> dict[str, Any]: ...

    def get_health_trend(self) -> dict[str, Any]: ...

    def get_status_heatmap(self, days: int = 30) -> dict[str, Any]: ...

    def set_run_state(self, run_id: str, state: str, finished_at: str | None = None) -> None: ...

    def append_progress(self, stream_id: str, line: str) -> int: ...

    def get_progress(self, stream_id: str, after_id: int = 0) -> list[dict[str, Any]]: ...

    def begin_operation(self, op_id: str, kind: str, created_by: str = "") -> bool: ...

    def finish_operation(
        self,
        op_id: str,
        state: str,
        result_json: str | None = None,
        error: str | None = None,
    ) -> None: ...

    def get_operation(self, op_id: str) -> dict[str, Any] | None: ...

    def get_compliance(self, product: str) -> dict[str, Any] | None: ...

    def set_compliance(self, product: str, version: str, compliance: str, run_id: str) -> None: ...

    def get_diagnostics(self, run_id: str, check_name: str | None = None) -> list[dict[str, Any]]: ...
