-- Remote-Migration 001 — Gate-Infrastruktur im Signal-eigenen Open-SQL-Schema.
-- Nummerierte Reihe analog store/migrations: NIE editieren, nur anhängen.
-- '{signal_schema}' wird zur Laufzeit gebunden (G2 — kein Schema-Literal);
-- nur Signals Space-User schreibt diese Tabellen (ADR-0002-Amendment).

-- Aktueller Gate-Zustand je Prüfobjekt (Upsert durch Signal nach jedem Lauf).
CREATE TABLE "{signal_schema}"."DQ_GATE_STATUS" (
  "OBJECT_ID"        NVARCHAR(256) PRIMARY KEY,
  "CONTRACT_ID"      NVARCHAR(128),
  "CONTRACT_VERSION" NVARCHAR(32),
  "RUN_ID"           NVARCHAR(64)  NOT NULL,
  "GATE_VERDICT"     NVARCHAR(16)  NOT NULL,
  "OVERALL_STATUS"   NVARCHAR(16)  NOT NULL,
  "MANIFEST_HASH"    NVARCHAR(64),
  "GENERATION"       INTEGER,
  "EVALUATED_AT"     TIMESTAMP     NOT NULL,
  "EXPIRES_AT"       TIMESTAMP
);

-- Append-only-Historie der Gate-Entscheidungen (Audit, Trend, Debugging).
CREATE TABLE "{signal_schema}"."DQ_GATE_STATUS_HISTORY" (
  "SEQ"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OBJECT_ID"        NVARCHAR(256) NOT NULL,
  "CONTRACT_ID"      NVARCHAR(128),
  "CONTRACT_VERSION" NVARCHAR(32),
  "RUN_ID"           NVARCHAR(64)  NOT NULL,
  "GATE_VERDICT"     NVARCHAR(16)  NOT NULL,
  "OVERALL_STATUS"   NVARCHAR(16)  NOT NULL,
  "MANIFEST_HASH"    NVARCHAR(64),
  "GENERATION"       INTEGER,
  "EVALUATED_AT"     TIMESTAMP     NOT NULL,
  "EXPIRES_AT"       TIMESTAMP
);
