-- Remote-Migration 003 — Healing-Audit (Konzept_Manuelles_Healing §3.1).
-- Reihe analog 001/002: NIE editieren, nur anhängen. '{signal_schema}' wird
-- zur Laufzeit gebunden (G2) — nur Signals Space-User schreibt diese Tabelle.

-- Append-only-Audit jeder Zeilen-Korrektur in einer Quarantäne-Parkbucht.
-- Zwei Quellen: 'api' (Signal-Cockpit, zusätzlich im Result-Store auditiert)
-- und 'procedure' (P_DQ_CORRECT_ROW, die SQL-seitige Tür ohne Tabellen-Grant).
CREATE TABLE "{signal_schema}"."DQ_HEAL_LOG" (
  "SEQ"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TABLE_NAME"   NVARCHAR(128) NOT NULL,
  "EPISODE_ID"   INTEGER       NOT NULL,
  "KEY_COLUMN"   NVARCHAR(128) NOT NULL,
  "KEY_VALUE"    NVARCHAR(5000),
  "COLUMN_NAME"  NVARCHAR(128) NOT NULL,
  "NEW_VALUE"    NVARCHAR(5000),
  "REASON"       NVARCHAR(500),
  "ACTOR"        NVARCHAR(128) NOT NULL,
  "CORRECTED_AT" TIMESTAMP     NOT NULL,
  "SOURCE"       NVARCHAR(16)  NOT NULL
);
